/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Key Management API
 * API für API-Key-Verwaltung, Usage-Tracking und Document Intelligence
 * OpenAPI spec version: 1.0.0
 */

export type AIRequestParamsGroupByParameterItem =
  (typeof AIRequestParamsGroupByParameterItem)[keyof typeof AIRequestParamsGroupByParameterItem]

export const AIRequestParamsGroupByParameterItem = {
  day: 'day',
  month: 'month',
  year: 'year',
  tag: 'tag',
  apikey: 'apikey',
  model: 'model',
  user: 'user',
} as const
