/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Key Management API
 * API für API-Key-Verwaltung, Usage-Tracking und Document Intelligence
 * OpenAPI spec version: 1.0.0
 */

export type AIRequestParamsModelTypeParameter =
  (typeof AIRequestParamsModelTypeParameter)[keyof typeof AIRequestParamsModelTypeParameter]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AIRequestParamsModelTypeParameter = {
  CompletionModelUsage: 'CompletionModelUsage',
  EmbeddingModelUsage: 'EmbeddingModelUsage',
  ImageModelUsage: 'ImageModelUsage',
} as const
