/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Key Management API
 * API für API-Key-Verwaltung, Usage-Tracking und Document Intelligence
 * OpenAPI spec version: 1.0.0
 */

export type AIRequestParamsGroupByParameterItem = typeof AIRequestParamsGroupByParameterItem[keyof typeof AIRequestParamsGroupByParameterItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AIRequestParamsGroupByParameterItem = {
  day: 'day',
  month: 'month',
  year: 'year',
  tag: 'tag',
  apiKey: 'apiKey',
  model: 'model',
  user: 'user',
} as const;
