/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Key Management API
 * API für API-Key-Verwaltung, Usage-Tracking und Document Intelligence
 * OpenAPI spec version: 1.0.0
 */
import type { AIRequestParamsGroupByParameterItem } from './aIRequestParamsGroupByParameterItem';

/**
 * Comma separated list of parameters to group by: day|month|year|[tag|apikey|model|user]
 */
export type AIRequestParamsGroupByParameter = AIRequestParamsGroupByParameterItem[];
