/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Key Management API
 * API für API-Key-Verwaltung, Usage-Tracking und Document Intelligence
 * OpenAPI spec version: 1.0.0
 */

export type AIRequestParamsUsageTypeParameter =
  (typeof AIRequestParamsUsageTypeParameter)[keyof typeof AIRequestParamsUsageTypeParameter]

export const AIRequestParamsUsageTypeParameter = {
  COMPLETION_USAGE: 'COMPLETION_USAGE',
  EMBEDDING_USAGE: 'EMBEDDING_USAGE',
  IMAGE_USAGE: 'IMAGE_USAGE',
} as const
