/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Key Management API
 * API für API-Key-Verwaltung, Usage-Tracking und Document Intelligence
 * OpenAPI spec version: 1.0.0
 */
import type { ModelUsageType } from './modelUsageType'

export interface AIUsageSummaryRecord {
  type?: ModelUsageType
  tag?: string
  model?: string
  technicalUserId?: string
  apiKeyId?: string
  day?: number
  month?: number
  year?: number
  requests?: number
  requestTokens?: number
  responseTokens?: number
  totalTokens?: number
  cost?: number
}
