/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Key Management API
 * API für API-Key-Verwaltung, Usage-Tracking und Document Intelligence
 * OpenAPI spec version: 1.0.0
 */
import type { AIUsageRecord } from './aIUsageRecord'
import type { PaginationInfo } from './paginationInfo'

export interface AIUsagePage {
  data?: AIUsageRecord[]
  pagination?: PaginationInfo
}
