/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Key Management API
 * API für API-Key-Verwaltung, Usage-Tracking und Document Intelligence
 * OpenAPI spec version: 1.0.0
 */
import type { ModelUsageType } from './modelUsageType'
import type { AIUsageRecordQuality } from './aIUsageRecordQuality'

export interface AIUsageRecord {
  type?: ModelUsageType
  tag?: string
  model?: string
  modelName?: string
  createDate?: string
  day?: number
  month?: number
  year?: number
  technicalUserId?: string
  apiKeyId?: string
  requests?: number
  tokensIn?: number
  tokensOut?: number
  totalTokens?: number
  cost?: number
  /** Image width (only for ImageModelUsage) */
  sizeWidth?: number
  /** Image height (only for ImageModelUsage) */
  sizeHeight?: number
  /** Image quality (only for ImageModelUsage) */
  quality?: AIUsageRecordQuality
}
