/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Key Management API
 * API für API-Key-Verwaltung, Usage-Tracking und Document Intelligence
 * OpenAPI spec version: 1.0.0
 */

/**
 * Image quality (only for ImageModelUsage)
 */
export type AIUsageRecordQuality = (typeof AIUsageRecordQuality)[keyof typeof AIUsageRecordQuality]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AIUsageRecordQuality = {
  standard: 'standard',
  hd: 'hd',
} as const
