/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Key Management API
 * API für API-Key-Verwaltung, Usage-Tracking und Document Intelligence
 * OpenAPI spec version: 1.0.0
 */

/**
 * End date of the time interval (UTC). If left empty it uses the latest known date.
 */
export type CommonRequestParamsToDateParameter = string;
