/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Key Management API
 * API für API-Key-Verwaltung, Usage-Tracking und Document Intelligence
 * OpenAPI spec version: 1.0.0
 */

/**
 * Page number for pagination (1-based).
 */
export type CommonRequestParamsPageParameter = number;
