/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Key Management API
 * API für API-Key-Verwaltung, Usage-Tracking und Document Intelligence
 * OpenAPI spec version: 1.0.0
 */

/**
 * Operation status for Document Intelligence extraction
 */
export type DocumentIntelligenceOperationStatus =
  (typeof DocumentIntelligenceOperationStatus)[keyof typeof DocumentIntelligenceOperationStatus]

export const DocumentIntelligenceOperationStatus = {
  processing: 'processing',
  completed: 'completed',
  failed: 'failed',
  canceled: 'canceled',
  skipped: 'skipped',
} as const
