/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Key Management API
 * API für API-Key-Verwaltung, Usage-Tracking und Document Intelligence
 * OpenAPI spec version: 1.0.0
 */
import type { DocumentIntelligenceOperationStatus } from './documentIntelligenceOperationStatus'

export interface ExtractionUsageSummaryRecord {
  status?: DocumentIntelligenceOperationStatus
  tag?: string
  provider?: string
  modelId?: string
  technicalUserId?: string
  apiKeyId?: string
  day?: number
  month?: number
  year?: number
  /** Number of extraction operations */
  operations?: number
  /** Total number of pages processed */
  totalPages?: number
  /** Average confidence score */
  averageConfidence?: number
  cost?: number
}
