/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Key Management API
 * API für API-Key-Verwaltung, Usage-Tracking und Document Intelligence
 * OpenAPI spec version: 1.0.0
 */

export interface ExtractedField {
  /** Name of the extracted field (e.g., "Rechnungsnummer", "Datum", "Betrag") */
  fieldName?: string
  /** Extracted value */
  value?: string
  /**
   * Confidence score for this specific field
   * @minimum 0
   * @maximum 1
   */
  confidence?: number
}
