/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Key Management API
 * API für API-Key-Verwaltung, Usage-Tracking und Document Intelligence
 * OpenAPI spec version: 1.0.0
 */

export type ExtractionRequestParamsGroupByParameterItem = typeof ExtractionRequestParamsGroupByParameterItem[keyof typeof ExtractionRequestParamsGroupByParameterItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ExtractionRequestParamsGroupByParameterItem = {
  day: 'day',
  month: 'month',
  year: 'year',
  tag: 'tag',
  apiKey: 'apiKey',
  provider: 'provider',
  modelId: 'modelId',
  user: 'user',
} as const;
