/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Key Management API
 * API für API-Key-Verwaltung, Usage-Tracking und Document Intelligence
 * OpenAPI spec version: 1.0.0
 */
import type { DocumentIntelligenceOperationStatus } from './documentIntelligenceOperationStatus';
import type { ExtractedField } from './extractedField';

export interface ExtractionUsageRecord {
  /** Unique identifier for the extraction operation */
  id?: string;
  /** Operation ID for tracking */
  operationId?: string;
  status?: DocumentIntelligenceOperationStatus;
  createDate?: string;
  /** @nullable */
  completedDate?: string | null;
  day?: number;
  month?: number;
  year?: number;
  userId?: string;
  apiKeyId?: string;
  tag?: string;
  provider?: string;
  modelId?: string;
  documentType?: string;
  pages?: number;
  extractedFields?: ExtractedField[];
  /**
   * Overall confidence score for the extraction
   * @minimum 0
   * @maximum 1
   */
  confidenceScore?: number;
  cost?: number;
}
