/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Key Management API
 * API für API-Key-Verwaltung, Usage-Tracking und Document Intelligence
 * OpenAPI spec version: 1.0.0
 */

export type ModelUsageType = (typeof ModelUsageType)[keyof typeof ModelUsageType]

export const ModelUsageType = {
  CompletionModelUsage: 'CompletionModelUsage',
  EmbeddingModelUsage: 'EmbeddingModelUsage',
  ImageModelUsage: 'ImageModelUsage',
} as const
