/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Key Management API
 * API für API-Key-Verwaltung, Usage-Tracking und Document Intelligence
 * OpenAPI spec version: 1.0.0
 */

export interface PaginationInfo {
  /** Current page number (1-based) */
  page?: number
  /** Number of items per page */
  limit?: number
  /** Total number of items */
  total?: number
  /** Total number of pages */
  totalPages?: number
}
