/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API Key Management API
 * API für API-Key-Verwaltung, Usage-Tracking und Document Intelligence
 * OpenAPI spec version: 1.0.0
 */
import type { CommonRequestParamsFromDateParameter } from './commonRequestParamsFromDateParameter';
import type { CommonRequestParamsToDateParameter } from './commonRequestParamsToDateParameter';
import type { CommonRequestParamsPageParameter } from './commonRequestParamsPageParameter';
import type { CommonRequestParamsLimitParameter } from './commonRequestParamsLimitParameter';
import type { CommonRequestParamsUserIdParameter } from './commonRequestParamsUserIdParameter';
import type { CommonRequestParamsTagParameter } from './commonRequestParamsTagParameter';
import type { CommonRequestParamsApiKeyIdParameter } from './commonRequestParamsApiKeyIdParameter';
import type { AIRequestParamsModelParameter } from './aIRequestParamsModelParameter';
import type { AIRequestParamsUsageTypeParameter } from './aIRequestParamsUsageTypeParameter';
import type { AIRequestParamsGroupByParameter } from './aIRequestParamsGroupByParameter';

export type UsageAISummaryGetV1Params = {
/**
 * Start date of the time interval (UTC). If left empty it uses the earliest known date.
 */
from_date?: CommonRequestParamsFromDateParameter;
/**
 * End date of the time interval (UTC). If left empty it uses the latest known date.
 */
to_date?: CommonRequestParamsToDateParameter;
/**
 * Page number for pagination (1-based).
 */
page?: CommonRequestParamsPageParameter;
/**
 * The number of items to return per page.
 */
limit?: CommonRequestParamsLimitParameter;
/**
 * Filter by user ID.
 */
userId?: CommonRequestParamsUserIdParameter;
/**
 * Filter by tag.
 */
tag?: CommonRequestParamsTagParameter;
/**
 * Filter by API key ID.
 */
apiKeyId?: CommonRequestParamsApiKeyIdParameter;
/**
 * Filter by model name.
 */
model?: AIRequestParamsModelParameter;
/**
 * Filter by usage type (COMPLETION_USAGE, EMBEDDING_USAGE, IMAGE_USAGE).
 */
usageType?: AIRequestParamsUsageTypeParameter;
/**
 * Comma separated list of parameters to group by: day|month|year|[tag|apiKey|model|user]
 */
by?: AIRequestParamsGroupByParameter;
};
